apiVersion: apps/v1
kind: Deployment
metadata:
  name: moonapp
  labels:
    app: moonapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moonapp
  template:
    metadata:
      labels:
        app: moonapp
    spec:
      containers:
        - name: moonapp
          image: thokil/moonapp:latest
          ports:
            - containerPort: 8082
          readinessProbe:
            httpGet:
              path: /
              port: 8082
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8082
            initialDelaySeconds: 10
            periodSeconds: 30

